### ISSUE TITLE
Is the license correct?

### ISSUE THREAD

**Issue by akx** [City-of-Helsinki/kuvaselaamo#6]
Right now Kuvaselaamo's copyright is assigned to "Haltu". Is that correct?

As I understand, the rest of the City-of-Helsinki projects are MIT...

https://github.com/City-of-Helsinki/kuvaselaamo/blob/8215fca8d85a3d1149d5506a12a0bd4b6a013643/LICENSE

**Comment by juyrjola** [comment]
The license should be MIT with copyrights assigned to the City of Helsinki.
